# Intake Bot {#Automatic-Legal-Intake}

#### Keywords

legal, intake, NLP 

## Legal Intake – A drag on providing services
Legal aid organizations do tremendous good. They help elders keep their Social Security, make sure wages get paid, and ensure that there is family support.
But determining which cases they can actually help requires a long and tedious process called intake, in which legal specialists field calls and messages from potential clients. Every day legal services specialists field nearly a hundred intake messages.
They must decide which messages represent actionable cases and which don’t. The process requires a lot of work, from determining the relevant area of law, to identifying legal elements required for a case, and finally assessing whether the elements are met. The longer the process takes, the fewer people are able to receive legal services they need to retain their benefits, immigration status, or even homes.

Intake Bot leverages natural language processing to automatically handle intake so that legal service organizations can focus their time on helping people.


## The Intake Bot Solution
Intake Bot is built upon years of intake data from legal services organizations across the country. Past cases are labeled by category and detail the back-and-forth conversations regarding the merits of each case. 

When new intake comes in, Intake Bot mines the intake message while comparing it with prior intakes. In the first processing step, a model is used to classify the message into one of three categories: meritorious, further communication, or unfruitful. 

Meritorious cases have a clear legal category and meet all the required elements. In the case of a meritorious classification, a cross-reference to WestLaw/LexisNexus is used to look up applicable, current caselaw and regulations and to extract the elements required for a client to get the outcome they want. Then, the case is immediately passed on to the appropriate division of the legal services organization with the case outlined by the elements with a summary of the information contained in the intake applicable to each element.

Further communication cases also have a defined legal category, but could use additional clarifying information to determine how promising they are. In this case, Intake Bot can respond to the intake submitter with an outline of what it believes the legal issue to be and where it requires more information. When the submitter responds, Intake Bot will repeat the process.

Unfruitful cases do not have clearly defined goal or legal issue. Here, Intake Bot would inform the submitter that their issue did not match a standard legal issue and could point them to more general help in the area if applicable. If the submitter believed their case to be valid, there could be an appeal process for them to get a manual review so that cases don't fall through the cracks.

## Fixing Intake Matters
Fielding a single intake can take up to 20 days of back and forth communication before it is determined to be a case worth pursuing. This triaging takes up valuable time that could be spent advocating for clients with meritorious cases. Intake Bot frees this time by automatically summarizing key elements of cases and requesting required information. Though there may be some unclear cases that require  review by a specialist, Intake Bot will make sure the best cases make it to the front of the line so lawyers can focus their time making a difference.
